platform:ios,'8.0'
target "HutHelper" do
    pod 'ASIHTTPRequest'
    pod 'MBProgressHUD', '~> 1.0.0'
    pod 'DJRefresh', '~> 1.0.5'
    pod 'UMengAnalytics-NO-IDFA'
    pod 'UMengUShare/Social/ReducedSina'
    pod 'UMengUShare/Social/ReducedWeChat'
    pod 'UMengUShare/Social/ReducedQQ'
    pod 'UMengUShare/UI'
    pod 'AFNetworking', '~> 3.0'
    pod 'MJRefresh'
    pod 'SDWebImage', '~>3.8'
    pod 'LGPlusButtonsView', '~> 1.1.0'
    pod 'TZImagePickerController'
    pod 'DTKDropdownMenu', '~> 0.0.4'
    pod 'YCXMenu', '~> 0.0.11'
    pod  'UITableView+FDTemplateLayoutCell'
    pod 'DZNEmptyDataSet'
    pod 'RongCloudIM/IMLib', '~> 2.8.3'
    pod 'RongCloudIM/IMKit', '~> 2.8.3'
end
